### ISSUE TITLE
Gradle integration?

### ISSUE THREAD

**Issue by photex** [ensime-tmp/ensime-src#15]
Is Ensime very tightly coupled to SBT? If it isn't I think that having a Gradle plugin would be a tremendously useful bit of kit. I'm willing to pitch in and take a stab at it but I wanted to get your opinions on the matter before diving in.

**Comment by photex** [comment]
As a test I've put together a very simple .ensime generator for my project and it works pretty well so far. At least it doesn't seem like it would much work to build a proper Gradle plugin.

``` groovy
// Generate .ensime
task ensime {
  doLast {
    def runtime_jars = project.configurations.runtime.resolve()
    def compile_jars = project.configurations.compile.resolve()
    def testCompile_jars = project.configurations.testCompile.resolve()

    println("(")
    println("  :subprojects (")
    println("    (")
    println("      :name \"${project.name}\"")
    println("      :module-name \"${project.name}\"")
    println("      :depends-on-modules ()")
    println("      :package \"<insert package name here>\"")
    println("      :version \"${project.version}\"")
    println("      :compile-deps (")
    for (jar in compile_jars) {
      print("        ") println("\"${jar.getAbsolutePath()}\"")
    }
    println("      )")
    println("      :runtime-deps (")
    for (jar in runtime_jars) {
      print("        ") println("\"${jar.getAbsolutePath()}\"")
    }
    println("      )")
    println("      :test-deps (")
    for (jar in testCompile_jars) {
      print("        ") println("\"${jar.getAbsolutePath()}\"")
    }
    println("      )")
    println("      :source-roots (")
    println("        \"${project.projectDir}/src/main/java\"")
    println("        \"${project.projectDir}/src/main/scala\"")
    println("        \"${project.projectDir}/src/test/java\"")
    println("        \"${project.projectDir}/src/test/scala\"")
    println("      )")
    println("      :target \"${project.buildDir}/classes/main\"")
    println("      :test-target \"${project.buildDir}/classes/test\"")
    println("    )")
    println("  )")
    println(")")
  }
}
```

**Comment by edani** [comment]
@photex There is very little coupling between ensime and sbt. The one aspect you found is the ensime-sbt-cmd module. The other one is the emacs ensime-sbt mode, whose main features are to decorate error messages with links to the source code, and key bindings to send commands to the sbt process ; also "run sbt compile on save" which is very convenient.

I don't use gradle but your example looks like it's on the right track. There isn't much to creating .ensime files. You may also wish to have ensime detect gradle projects and add the appropriate  key bindings.
