### ISSUE TITLE
Added ':sbt-compile-on-save-command'

### ISSUE THREAD

**Issue by Peluko** [ensime-tmp/ensime-src#4]
Hello.

I've been lately playing with [Scala.js](http://www.scala-js.org/). Scala.js compiles to javascript by issuing the sbt command `packageJS`. So I've added an option to the project definition file that lets specify the command issued to inferior sbt when saving scala files. The option is called `:sbt-compile-on-save-command`:

https://github.com/Peluko/ensime-src/commit/f2503262a4779de63332fa6beeceba8005194a9f

In my current setup I use [scala-js-workbench](https://github.com/lihaoyi/scala-js-workbench), so thanks to ensime's 'compile on save', whenever I edit a scala file on a Scala.js project, ensime automatically compiles the project and scala-js-workbech refresh the debugging browser.

**Comment by rajish** [comment]
Merged. Just give me a day to forward it to the package.
